-- AlterTable
ALTER TABLE "Rifle" ADD COLUMN "zeroDistanceM" DOUBLE PRECISION NOT NULL DEFAULT 100;
ALTER TABLE "Rifle" ADD COLUMN "clickCmAt100m" DOUBLE PRECISION NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "Recipe" DROP COLUMN "zeroDistanceM";
