-- AlterTable
ALTER TABLE "Recipe" ADD COLUMN "calculatedV0" DOUBLE PRECISION;
ALTER TABLE "Recipe" ADD COLUMN "measuredV0" DOUBLE PRECISION;
ALTER TABLE "Recipe" ADD COLUMN "fillRate" DOUBLE PRECISION;
